#!/bin/bash

set -e
set -o pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname "$0")/common.sh

# Read inputs
payload="$(cat <&0)"

# Prepare
setup_resource
echo "Resource setup successful."

[ -z "$registry" ] \
|| yarn_args="--registry $registry"

[ -n "$scope" ] \
&& fqpn="@$scope/$package" \
|| fqpn="$package"

result=`npm info \
    --json \
    "$fqpn" \
| jq '[{version:.["dist-tags"].latest}]'`

echo "$result" >&3

[ -n "$result" ] \
|| exit 1
