#!/bin/bash

set -e
set -o pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname "$0")/common.sh

# Read inputs
payload=$(mktemp request-payload.XXXXXX)
cat > $payload <&0

package=$(jq -r '.source.package // ""' < $payload)

if [ -z "$package" ]; then
  echo "invalid payload (missing package)"
  exit 1
fi

# Prepare
setup_resource $payload
echo "Resource setup successful."

yarn info \
    $yarn_args \
    --json \
    "$package" \
| jq '[{version:.data["dist-tags"].latest}]' \
>&3
