#!/bin/bash

set -e
set -o pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname "$0")/common.sh

# Read inputs
payload=$(mktemp $TMPDIR/request-payload.XXXXXX)
cat > $payload <&0

# Prepare
setup_resource
echo "Resource setup successful."

[ -z "$registry" ] \
|| yarn_args="--registry $registry"

[ -n "$scope" ] \
&& fqpn="@$scope/$package" \
|| fqpn="$package"

yarn info \
    $yarn_args \
    --json \
    "$fqpn" \
| jq '[{version:.data["dist-tags"].latest}]' \
>&3
