#!/bin/bash

set -e
set -o pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname "$0")/common.sh

# Read inputs
payload=$(mktemp $TMPDIR/request-payload.XXXXXX)
cat > $payload <&0

version_string=$(jq -r '.version.version // ""' < $payload)

if [ -z "$version_string" ]; then
  echo "invalid payload (missing version)"
  exit 1
fi

skip_download=$(jq -r '.source.skip_download // ""' < $payload)

# Prepare
setup_resource
echo "Resource setup successful."

[ -n "$scope" ] \
&& fqpn="@$scope/$package" \
|| fqpn="$package"

if [ "$skip_download" = "true" ]; then
  echo "Skipping download"
else
  echo "Loading package $fqpn version $version_string"
  yarn add \
    $yarn_args \
    --link-folder $1/link-folder \
    --global-folder $1/global-folder \
    --modules-folder $1/node_modules \
    --cache-folder $1/cache-folder \
    "$fqpn@$version_string"
fi

echo "$version_string" \
> $1/version

echo "{\"version\":{\"version\":\"$version_string\"}}" \
| jq . \
>&3
